
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 29 04:00:54 CST 2021
//----------------------------------------------------

package codigoPLSQL;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Trim = 19;
  public static final int Return = 47;
  public static final int When = 30;
  public static final int Into = 35;
  public static final int Op_Logico = 60;
  public static final int Op_Atribucion = 62;
  public static final int Op_Booleano = 64;
  public static final int Punto = 3;
  public static final int Count = 16;
  public static final int Char = 79;
  public static final int Each = 43;
  public static final int For = 42;
  public static final int Else = 22;
  public static final int Values = 54;
  public static final int Binary = 8;
  public static final int Create = 39;
  public static final int ERROR = 77;
  public static final int Parentesis_Der = 66;
  public static final int Update = 32;
  public static final int Insert = 83;
  public static final int Begin = 12;
  public static final int Date = 82;
  public static final int Commit = 51;
  public static final int Exit = 28;
  public static final int Desc = 49;
  public static final int Corchete_Der = 70;
  public static final int Llave_Der = 68;
  public static final int Trigger = 38;
  public static final int Function = 46;
  public static final int End = 11;
  public static final int Before = 45;
  public static final int Op_Multiplicacion = 58;
  public static final int Op_Relacional = 61;
  public static final int Close = 37;
  public static final int Table = 10;
  public static final int Open = 36;
  public static final int P_Coma = 71;
  public static final int If = 21;
  public static final int Texto = 76;
  public static final int Elsif = 23;
  public static final int EOF = 0;
  public static final int By = 7;
  public static final int Real = 75;
  public static final int From = 33;
  public static final int Last = 14;
  public static final int Numero = 74;
  public static final int Op_Igual = 55;
  public static final int Type = 4;
  public static final int First = 13;
  public static final int Integer = 9;
  public static final int Dos_Puntos = 72;
  public static final int Declare = 6;
  public static final int Op_Division = 59;
  public static final int Op_Suma = 56;
  public static final int error = 1;
  public static final int Parentesis_Izq = 65;
  public static final int Asc = 48;
  public static final int Next = 18;
  public static final int Row = 44;
  public static final int Comillas = 2;
  public static final int Dual = 34;
  public static final int As = 41;
  public static final int Varchar2 = 80;
  public static final int Identificador = 73;
  public static final int Savepoint = 53;
  public static final int Corchete_Izq = 69;
  public static final int Select = 29;
  public static final int Number = 78;
  public static final int Llave_Izq = 67;
  public static final int Others = 31;
  public static final int Rollback = 52;
  public static final int Loop = 26;
  public static final int Exists = 15;
  public static final int Op_Incremento = 63;
  public static final int Alter = 40;
  public static final int Delete = 20;
  public static final int Index = 5;
  public static final int Order = 50;
  public static final int Then = 24;
  public static final int Goto = 25;
  public static final int While = 27;
  public static final int Op_Resta = 57;
  public static final int Boolean = 81;
  public static final int Prior = 17;
}

