/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import static Inicio.Inicio.principal;
import codigo.FrmInicioC;
import codigoHTML.FrmInicioHTML;
import codigoP.FrmInicioP;
import codigoPLSQL.FrmInicioPLSQL;
import codigoSQL.FrmInicioSQL;
import codigoj.FrmInicioJ;



/**
 *
 * @author jcora
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
    }
    public static FrmInicioC principalC=new FrmInicioC();
    
    public static FrmInicioJ principalJ=new FrmInicioJ();
    
    public static FrmInicioHTML principalHTML=new FrmInicioHTML();
       public static FrmInicioP principalP=new FrmInicioP();
    public static FrmInicioPLSQL principalPLSQL=new FrmInicioPLSQL();
    public static FrmInicioSQL principalSQL=new FrmInicioSQL();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnHTML = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnJavaScript = new javax.swing.JButton();
        btnPLSQL = new javax.swing.JButton();
        btnTSQL = new javax.swing.JButton();
        btnPascal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 48)); // NOI18N
        jLabel1.setText("******* Compilador *******");

        btnHTML.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        btnHTML.setText("HTML");
        btnHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHTMLActionPerformed(evt);
            }
        });

        btnC.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        btnC.setText("C++");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnJavaScript.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        btnJavaScript.setText("JavaScript");
        btnJavaScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJavaScriptActionPerformed(evt);
            }
        });

        btnPLSQL.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        btnPLSQL.setText("PL/SQL");
        btnPLSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPLSQLActionPerformed(evt);
            }
        });

        btnTSQL.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        btnTSQL.setText("T-SQL");
        btnTSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTSQLActionPerformed(evt);
            }
        });

        btnPascal.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        btnPascal.setText("Pascal");
        btnPascal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPascalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnC)
                        .addGap(79, 79, 79)
                        .addComponent(btnJavaScript)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPLSQL))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTSQL)
                                .addGap(42, 42, 42)
                                .addComponent(btnPascal)
                                .addGap(62, 62, 62)
                                .addComponent(btnHTML))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1)))
                        .addGap(69, 69, 69)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnC)
                    .addComponent(btnJavaScript)
                    .addComponent(btnPLSQL))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTSQL)
                    .addComponent(btnPascal)
                    .addComponent(btnHTML))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
 
        principalC.correrInterfazC();
    }//GEN-LAST:event_btnCActionPerformed

    private void btnJavaScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJavaScriptActionPerformed
             principalJ.correrInterfazJ();
    }//GEN-LAST:event_btnJavaScriptActionPerformed

    private void btnHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHTMLActionPerformed
         principalHTML.correrInterfazHTML();
    }//GEN-LAST:event_btnHTMLActionPerformed

    private void btnPascalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPascalActionPerformed
      principalP.correrInterfazP();  // TODO add your handling code here:
    }//GEN-LAST:event_btnPascalActionPerformed

    private void btnPLSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPLSQLActionPerformed
         principalPLSQL.correrInterfazPLSQL();   // TODO add your handling code here:
    }//GEN-LAST:event_btnPLSQLActionPerformed

    private void btnTSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTSQLActionPerformed
        principalSQL.correrInterfazSQL();  // TODO add your handling code here:
    }//GEN-LAST:event_btnTSQLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    
    }
     public void correrInterfaz() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnHTML;
    private javax.swing.JButton btnJavaScript;
    private javax.swing.JButton btnPLSQL;
    private javax.swing.JButton btnPascal;
    private javax.swing.JButton btnTSQL;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
