
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 28 23:30:52 CST 2021
//----------------------------------------------------

package codigoHTML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Input = 35;
  public static final int H6 = 30;
  public static final int H5 = 29;
  public static final int H4 = 28;
  public static final int H3 = 27;
  public static final int H2 = 26;
  public static final int H1 = 25;
  public static final int Op_Logico = 77;
  public static final int Small = 52;
  public static final int Op_Booleano = 81;
  public static final int Op_Atribucion = 79;
  public static final int Basefont = 6;
  public static final int Textarea = 60;
  public static final int Cite = 15;
  public static final int Li = 40;
  public static final int Punto = 8;
  public static final int Caption = 13;
  public static final int Script = 50;
  public static final int Strong = 54;
  public static final int Basefront = 98;
  public static final int Div = 20;
  public static final int Title = 62;
  public static final int Kbd = 38;
  public static final int Area = 5;
  public static final int Dir = 19;
  public static final int Em = 22;
  public static final int Map = 41;
  public static final int Form = 24;
  public static final int Blockquote = 9;
  public static final int Link = 39;
  public static final int ERROR = 99;
  public static final int Parentesis_Der = 83;
  public static final int Option = 45;
  public static final int Slect = 97;
  public static final int Big = 7;
  public static final int Menu = 42;
  public static final int Body = 10;
  public static final int Data = 71;
  public static final int Dl = 21;
  public static final int Corchete_Der = 87;
  public static final int Llave_Der = 85;
  public static final int Dd = 17;
  public static final int Head = 31;
  public static final int Pre = 47;
  public static final int Img = 34;
  public static final int Base = 69;
  public static final int Op_Multiplicacion = 75;
  public static final int Code = 16;
  public static final int Meta = 43;
  public static final int Op_Relacional = 78;
  public static final int U = 66;
  public static final int Param = 46;
  public static final int Table = 58;
  public static final int P = 48;
  public static final int P_Coma = 88;
  public static final int Ol = 44;
  public static final int I = 37;
  public static final int Texto = 93;
  public static final int Ul = 96;
  public static final int EOF = 0;
  public static final int B = 12;
  public static final int Real = 92;
  public static final int Address = 3;
  public static final int Numero = 91;
  public static final int Time = 70;
  public static final int Op_Igual = 72;
  public static final int Br = 11;
  public static final int Dos_Puntos = 89;
  public static final int Hr = 32;
  public static final int Op_Division = 76;
  public static final int Appelt = 4;
  public static final int Op_Suma = 73;
  public static final int Dfn = 18;
  public static final int Center = 14;
  public static final int error = 1;
  public static final int Parentesis_Izq = 82;
  public static final int Tt = 64;
  public static final int Tr = 63;
  public static final int Comillas = 2;
  public static final int Noscript = 68;
  public static final int UL = 65;
  public static final int sup = 94;
  public static final int Sup = 57;
  public static final int Th = 61;
  public static final int Td = 59;
  public static final int Strike = 53;
  public static final int Sindex = 36;
  public static final int Samp = 49;
  public static final int Identificador = 90;
  public static final int Isindex = 95;
  public static final int Corchete_Izq = 86;
  public static final int Select = 51;
  public static final int Llave_Izq = 84;
  public static final int Font = 23;
  public static final int Stype = 55;
  public static final int Sub = 56;
  public static final int Op_Incremento = 80;
  public static final int Var = 67;
  public static final int Op_Resta = 74;
  public static final int Html = 33;
}

